name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GOPATH: /home/runner/work/go
    steps:
      - uses: actions/checkout@v3
#      - uses: styfle/cancel-workflow-action@0.11.0
#        with:
#          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-test
      - id: go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: "go.mod"
#      - name: Run lint
#        run: |
#          make lint
      - name: Run test
        run: |
          go test -v ./...
#      - name: Upload coverage to codecov
#        uses: codecov/codecov-action@a1ed4b322b4b38cb846afb5a0ebfa17086917d27
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./coverage.txt
#          fail_ci_if_error: false